<?php
$modversion['name'] = _MI_PLAYHIST_NAME;
$modversion['dirname'] = 'xplayhistory';
$modversion['description'] = _MI_PLAYHIST_DESC;
$modversion['version'] = '0.1';
$modversion['author'] = 'Marco Garbelini <marco@garbelini.net><br>http://www.garbelini.net';
$modversion['credits'] = 'Marco Garbelini <marco@garbelini.net><br>http://www.garbelini.net';
$modversion['license'] = 'GNU/GPL';
$modversion['official'] = 'No';
$modversion['image'] = 'images/xplayhistory_logo.gif';

// Sql file (must contain sql generated by phpMyAdmin)
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Tables created by sql file
$modversion['tables'][0] = 'play_history';

// Menu
$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = _MI_MENU_STATS;
$modversion['sub'][1]['url'] = 'stats.php';

// Templates
$modversion['templates'][1]['file'] = 'xplayhist_index.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'xplayhist_stats.html';
$modversion['templates'][2]['description'] = '';

// Parameters
$modversion['hasAdmin'] = 1;
$modversion['config'][1]['name'] = 'numberOfSongs';
$modversion['config'][1]['title'] = '_MI_NUMBER_OF_SONGS';
$modversion['config'][1]['description'] = '';
$modversion['config'][1]['formtype'] = 'select';
$modversion['config'][1]['valuetype'] = 'int';
$modversion['config'][1]['default'] = 10;
$modversion['config'][1]['options'] = ['10' => 10, '20' => 20, '30' => 30, '50' => 50, '100' => 100];

$modversion['config'][2]['name'] = 'consecutiveDuplicates';
$modversion['config'][2]['title'] = '_MI_CONSECUTIVE_DUPLICATES';
$modversion['config'][2]['description'] = '_MI_CONSECUTIVE_DUPLICATES_DESC';
$modversion['config'][2]['formtype'] = 'yesno';
$modversion['config'][2]['default'] = 0;

$modversion['config'][3]['name'] = 'shameList';
$modversion['config'][3]['title'] = '_MI_SHAME_LIST';
$modversion['config'][3]['description'] = '_MI_SHAME_LIST_DESC';
$modversion['config'][3]['formtype'] = 'textarea';
$modversion['config'][3]['default'] = '';

$modversion['config'][4]['name'] = 'minimumTimeSpacing';
$modversion['config'][4]['title'] = '_MI_MINIMUM_TIME_SPACING';
$modversion['config'][4]['description'] = '_MI_MINIMUM_TIME_SPACING_DESC';
$modversion['config'][4]['formtype'] = 'select';
$modversion['config'][4]['valuetype'] = 'int';
$modversion['config'][4]['default'] = 10;
$modversion['config'][4]['options'] = ['0' => 0, '5' => 5, '10' => 10, '30' => 30, '60' => 60, '90' => 90];
